frontend:
  replicaCount: 1
  image:
    repository: 203071037199.dkr.ecr.ap-south-1.amazonaws.com/mern-frontend
    tag: v1
  service:
    port: 80

backend:
  replicaCount: 1
  image:
    repository: 203071037199.dkr.ecr.ap-south-1.amazonaws.com/mern-backend
    tag: v1
  service:
    port: 5000

ingress:
  enabled: true
  host: mern.example.com   # temporary, will use ALB DNS first
